stages:
  - export

tanker/stable:
  stage: export
  script:
    - python3 -m pipenv install
    - python3 -m pipenv run conan user --clean tanker
    - python3 -m pipenv run conan user --remote godzilla --password ${CONAN_GODZILLA_TANKER_PASSWORD} tanker
    - python3 -m pipenv run conan export . tanker/stable
      # get the reference of the current package
    - python3 -m pipenv run conan upload $(python3 -m pipenv run conan info . 2> /dev/null | head -n 1) --remote godzilla
  only:
    - tags
  when: manual
  tags:
    - linux
    - debian9
