image: tanker.local:5000/ci-cpp:latest

before_script:
  - dmenv install

stages:
  - build
  - deploy

build/linux:
  stage: build
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py build-and-test --profile gcc8

build/macos:
  stage: build
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py build-and-test --profile macos

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
