before_script:
  - dmenv install

stages:
  - build

build/linux:
  stage: build
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py --profile gcc8

build/macos:
  stage: build
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py --profile macos
