image: registry.gitlab.com/tankerhq/docker/native:latest

before_script:
  - poetry run python -m pip install --upgrade pip
  - poetry install

stages:
  - build
  - deploy

.build:
  stage: build
  except:
    - schedules

build/linux:
  extends: .build
  tags:
    - linux
    - tanker
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile linux-release

build/macos:
  extends: .build
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/windows:
  extends: .build
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release

coverage:
  stage: build
  only:
    - schedules
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile linux-debug --coverage
    - mv build/linux-debug/x86_64/Release/coverage coverage
  tags:
    - linux
    - tanker
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - poetry run python run-ci.py mirror
