[tool.poetry]
name = "tconcurrent"
version = "0.0.0"
description = "C++ async framework"
authors = ["Tanker team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
tankerci = "*"


[[tool.poetry.source]]
name = "tanker.local"
url = "http://tanker.local:8181"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
