[version]
current = "0.13"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  (
    -
    (?P<lifecycle>alpha|beta|r)
    (?P<release>\d+)
  )?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "conanfile.py"
search = 'version = "{current_version}"'

[[file]]
src = ".gitlab-ci.yml"
search = '    - python3 -m pipenv run conan upload tconcurrent/{current_version}@tanker/stable --remote godzilla'
